    <BR>
  </TD>
  <TD WIDTH=10 BGCOLOR="#000000">&nbsp;</TD>
</TR>
<TR>
  <TD WIDTH=10 HEIGHT=30 BGCOLOR="#000000">&nbsp;</TD>
  <TD COLSPAN=3 ROWSPAN=2 HEIGHT=40 BGCOLOR="#000000" ALIGN=CENTER>
    <?php
      Bouton("", "accueil");
      Bouton("Films/", "films");
      Bouton("Gens/", "gens");
      Bouton("FAQ/", "faq");
    ?>
  </TD>
  <TD WIDTH=10 HEIGHT=30 BGCOLOR="#000000">&nbsp;</TD>
</TR>
<TR>
  <TD WIDTH=10 HEIGHT=10 BGCOLOR="#000000"><IMG SRC="Images/Cadre/bg.gif" WIDTH=10 HEIGHT=10></TD>
  <TD WIDTH=10 HEIGHT=10 BGCOLOR="#000000"><IMG SRC="Images/Cadre/bd.gif" WIDTH=10 HEIGHT=10></TD>
</TR>
</TABLE>

  </TD>
</TR>
</TABLE>
</BODY>

</HTML>